blank_issues_enabled: false
contact_links:
  - name: Red Witch Discussions
    url: https://github.com/Floating-Eye-Software/redwitch/discussions
    about: Use Red Witch Discussions for questions, feedback, or feature ideas related to the QMS or Red Witch.
